# Generated by Django 5.0 on 2023-12-29 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPeones.peon')),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPeones.contrato')),
            ],
        ),
    ]
