# Generated by Django 5.0 on 2023-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPeones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peon',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
