# Generated by Django 5.0 on 2023-12-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPeones', '0002_peon_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlPeones.contrato'),
        ),
    ]
