# Generated by Django 5.0 on 2023-12-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlPeones', '0003_alter_retiro_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='peon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlPeones.peon'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlPeones.contrato'),
        ),
    ]
